from django.contrib import admin
from django.urls import path
from . import views
from . import db
urlpatterns = [

    path('', views.index, name='index'),
    path('register_page', views.register_page, name='register_page'),
    path('register', views.register, name='register'),
    path('login_page', views.login_page, name='login_page'),
    path('login', views.login, name='login'),
    path('student_page', views.student_page, name='student_page'),
    path('admin', views.admin, name='admin'),
    path('update_admin_profile', views.update_admin_profile,
         name='update_admin_profile'),
    path('delete_student/<int:id>/', views.delete_student, name='delete_student'),
    path('edit_student_profile/<int:id>/',
         views.edit_student_profile, name='edit_student_profile'),
    path('update_student_profile', views.update_student_profile,
         name='update_student_profile'),
    path('manage_universities', views.manage_universities,
         name='manage_universities'),
    path('add_university_form', views.add_university_form,
         name='add_university_form'),
    path('edit_universities/<int:id>/',
         views.edit_universities, name='edit_universities'),
    path('delete_universities/<int:id>/',
         views.delete_universities, name='delete_universities'),
    path('filter_unis_by_city/<int:id>/',
         views.filter_unis_by_city, name='filter_unis_by_city'),
    path('merit_page/<int:id>/', views.merit_page, name='merit_page'),
    path('univeristy_details/<int:id>/',
         views.univeristy_details, name='univeristy_details'),
    path('logout', views.logout, name='logout'),
    path('search_universities', views.search_universities,
         name='search_universities'),
    path('delete_merit/<int:clg>/<int:id>/',
         views.delete_merit, name='delete_merit'),
    path('add_city', views.add_city, name='add_city'),
    path('import_modal', views.import_modal, name='import_modal'),
    path('recommendation', views.recommendation, name='recommendation'),
    path('user', views.user, name='user'),
    path('update_uesr_profile', views.update_uesr_profile,
         name='update_uesr_profile'),
    path('add_feedback', views.add_feedback, name='add_feedback'),
    path('Manage_feedback', views.Manage_feedback, name='Manage_feedback'),
    path('delete_feedback/<int:id>/',
         views.delete_feedback, name='delete_feedback'),
    path('add_to_wishlist/<int:id>/',
         views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist', views.wishlist, name='wishlist'),
    path('near_me', views.near_me, name='near_me'),
    path('delete_uni_from_wishlist/<int:id>/',views.delete_uni_from_wishlist, name='delete_uni_from_wishlist'),
    path('contact_page',views.contact_page, name='contact_page'),
    path('about_page',views.about_page, name='about_page'),
    path('send_mail',views.send_mail, name='send_mail'),
    path('mail_page',views.mail_page, name='mail_page'),
    path('delete_mail/<int:id>/',views.delete_mail, name='delete_mail'),
    path('admin_about_page',views.admin_about_page, name='admin_about_page'),
    path('add_about',views.add_about, name='add_about'),



]
