# Generated by Django 4.0.1 on 2022-07-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0002_university_city_id_university_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='high',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='university',
            name='high_avg',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='university',
            name='log_avg',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='university',
            name='low',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='university',
            name='medium',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='university',
            name='medium_avg',
            field=models.CharField(default='', max_length=300),
        ),
    ]
