# Generated by Django 4.0.1 on 2022-07-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0003_university_high_university_high_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cgpa',
            field=models.CharField(default='', max_length=300),
        ),
    ]
