# Generated by Django 4.1 on 2022-08-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0004_university_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='uni_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
